export default  { 
    grupo:[
    {nome:"Assistencias", 
    oc:["Doente Mental",
        "Parturiente",
        "Socorro de Urgência",
        "Outros",
    ]},
    {
    nome:"Contra Pessoa", 
    oc:[
        "Agressão Fisica",
        "Ameaça",
        "Homicídio",
        "Tentativa de homicídio",
        "Feminicídio",
        "Tentativa de feminicídio",
        "Latrocínio",
        "Suicídio",
        "Tentativa de suicídio",
        "Roubo a pessoa",
        "Roubo de celular",
        "Tentativa de roubo a pessoa",
        "Furto a pessoa",
        "Furto de celular",
        "Violencia doméstica",
        "Atrito familiar",
        "Atrito verbal",
        "Atrito conjugal",
        "Sequestro",
        "Extorsão mediante sequestro",
        "Lesão corporal",
        "Lesão corporal seguida de morte",
        "Outros",
        ]
    },
    {nome:"Contra Patrimonio", 
    oc:["Dano/Depredação/Vandalismo",
        "Invasão domiciliar",
        "Roubo a comércio",
        "Tentativa de roubo a comércio",
        "Furto a comércio",
        "Tentativa de furto a comércio",
        "Arrombamento a comércio",
        "Tent. de arrombamento a comércio",
        "Roubo a residência",
        "Tentativa de roubo a residência",
        "Furto a residência",
        "Tentativa de furto a residência",
        "Arrombamento a residência",
        "Tent. de arrombamento a residência",
        "Assalto a banco",
        "Tentativa de assalto a banco",
        "Assalto aos Correios",
        "Tentativa de assalto aos Correios",
        "Assalto a Lotérica",
        " Tentativa de assalto a Lotérica",
        "Explosão de caixa eletrônico",
        "Assalto a carro forte",
        "Tentativa de assalto a carro forte",
        "Roubo a ônibus",
        "Tentativa de roubo a ônibus",
        "Roubo a posto de combustível",
        "Tent. de roubo a posto de combustível",
        "Roubo de veículo",
        "Tentativa de roubo de veículo",
        "Furto de veículo",
        "Roubo de motocicleta",
        "Tentativa de roubo de motocicleta",
        "Furto de motocicleta",
        "Roubo de bicicleta",
        "Furto de bicicleta",
        ""

    ]},
    ]
    
 };
    
